### ISSUE TITLE
Run quickstart project with microk8s

### ISSUE THREAD

**Issue by adilsonatalla** [JanssenProject/home#11]
I'm running the quickstart project with microk8s to have a first contact with the tool.

The project is apparently running correctly, however, I can't access the service.
There is a comment in the README stating the following:

> This will install docker, microk8s, helm and Janssen with the default settings the can be found inside values.yaml. Please map the ip of the instance running ubuntu to demoexample.jans.io and then access the endpoints at your browser such in the example in the table below.

Could you describe better what mapping needs to be done? I did not understand for sure what is necessary to do to access the server.

Here is the list of all services running on microk8s:

![Screenshot from 2021-02-06 10-39-01](https://user-images.githubusercontent.com/13313054/107119630-ac813080-6867-11eb-88f2-43ccb8fd050d.png)
![Screenshot from 2021-02-06 10-39-17](https://user-images.githubusercontent.com/13313054/107119634-b014b780-6867-11eb-8f76-183fdb475d24.png)

**Comment by moabu** [comment]
Hi @adilsonatalla, 

This just simply means that you map your ip of the vm the microk8s is running on to the domain that was used in installation. The domain here would be `demoexample.jans.io`

Example:
`/etc/hosts`
```
192.168.2.2 demoexample.jans.io
```
