### ISSUE TITLE
Command to load test data as given in `development.md` returns an error

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/home#27]
Environment : 
OS: Ubuntu 20.04

If one follows sequence of commands as given in [development.md](), then command given below to load test data returns an error:
`python3 setup.py -t -n`

Error:
```
KeyError: 'config_api_scopes_list'

```

when attempted the same command second time:

```
shutil.Error: Destination path '/opt/jans/jans-cli/cli' already exists

```

`setup.log` and `setup_error.log` are attached.
[setup.log](https://github.com/JanssenProject/home/files/6684169/setup.log)
[setup_error.log](https://github.com/JanssenProject/home/files/6684171/setup_error.log)

**Comment by devrimyatar** [comment]
@ossdhaval Please also provide argument `-x`
I tested with `python3 setup.py -t -x -n`

![Screenshot_2021-06-21_15-58-10](https://user-images.githubusercontent.com/6398752/122766246-fb28e780-d2a9-11eb-988f-933d55a46105.png)

**Comment by ossdhaval** [comment]
Thanks you @mbaser for testing it out. I'll update development.md.

**Comment by ossdhaval** [comment]
Closed with [commit](https://github.com/JanssenProject/home/commit/2029ec59050809d4250206a4955738d4b156531f).
